# Use Ubuntu as the base image
FROM ubuntu:24.04  

# Install Nginx
RUN apt update && apt install -y nginx  

# Expose port 80
EXPOSE 80  

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]

