FROM ubuntu:22.04 AS maven
RUN apt update && \
    apt install openjdk-17-jdk -y && \
    apt install curl -y && \
    apt install tar -y  && \
    apt install wget -y && \
    wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz && \
    tar xzvf apache-maven-3.9.9-bin.tar.gz && \
    mkdir /usr/share/maven && \
    mv apache-maven-3.9.9 /usr/share/maven
ENV  M2_HOME="/usr/share/maven/apache-maven-3.9.9"
ENV  PATH="$M2_HOME/bin:$PATH"
CMD ["sh", "-c", "java -version && mvn -version"]   

FROM maven
ADD https://github.com/spring-projects/spring-petclinic.git /app
RUN cd app && \
    mvn clean package

